### ISSUE TITLE
Not working under github actions

### ISSUE THREAD

**Issue by alanfzf** [auvred/prettier-pnp#13]
Im not able to use it trough github actions, here is my .prettierrc and workflow file:

```json
{
    "tabWidth": 4,
    "semi": false,
    "singleQuote": false,
    "bracketSameLine": true,
    "htmlWhitespaceSensitivity": "ignore",
    "plugins": ["prettier-plugin-svelte"],
    "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

```yaml
name: code-format-checks
on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
jobs:
    formatting-checks:
        runs-on: ubuntu-latest
        container:
            image: node:alpine
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check JS file formatting
              run: npx prettier-pnp --pn svelte --check .

```

result:

![Image](https://github.com/user-attachments/assets/e31dd51b-1a72-468f-9e58-a3ff59a150cb)
